del Unit1.dcu /s
del classes.dex /s
del Project1.apk /s
del Project1.exe /s
del Project1.o /s
del Unit1.o /s
del libProject1.so /s
del Project1.aab /s
del resources.pb /s
del Project1.ipa /s
del Project1.dSYM /s
del Project1 /s
del Project1.rsm /s
del Project1.dproj.local /s
del Project1.identcache /s