//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JclBaseExpert-D.xml)
            
     Last generated: 22-09-2008  21:28:22 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#include <windows.h>
#pragma hdrstop
USEFORMNS("..\..\experts\common\JclOtaExceptionForm.pas", Jclotaexceptionform, JclExpertExceptionForm); 
USEFORMNS("..\..\experts\common\JclOtaConfigurationForm.pas", Jclotaconfigurationform, JclOtaOptionsForm); 
USEFORMNS("..\..\experts\common\JclOtaActionConfigureSheet.pas", Jclotaactionconfiguresheet, JclOtaActionConfigureFrame); /* TFrame: File Type */
USEFORMNS("..\..\experts\common\JclOtaUnitVersioningSheet.pas", Jclotaunitversioningsheet, JclOtaUnitVersioningFrame); /* TFrame: File Type */
USEFORMNS("..\..\experts\common\JclOtaWizardForm.pas", Jclotawizardform, JclWizardForm); 
USEFORMNS("..\..\experts\common\JclOtaWizardFrame.pas", Jclotawizardframe, JclWizardFrame); /* TFrame: File Type */
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------
//   Package source.
//---------------------------------------------------------------------------
#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

