//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JclRepositoryExpert-D.xml)
            
     Last generated: 03-01-2010  23:24:34 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#include <windows.h>
#pragma hdrstop
USEFORMNS("..\..\experts\repository\ExceptionDialog\JclOtaExcDlgWizard.pas", Jclotaexcdlgwizard, JclOtaExcDlgForm); 
USEFORMNS("..\..\experts\repository\ExceptionDialog\JclOtaExcDlgFileFrame.pas", Jclotaexcdlgfileframe, JclOtaExcDlgFilePage); /* TFrame: File Type */
USEFORMNS("..\..\experts\repository\ExceptionDialog\JclOtaExcDlgFormFrame.pas", Jclotaexcdlgformframe, JclOtaExcDlgFormPage); /* TFrame: File Type */
USEFORMNS("..\..\experts\repository\ExceptionDialog\JclOtaExcDlgSystemFrame.pas", Jclotaexcdlgsystemframe, JclOtaExcDlgSystemPage); /* TFrame: File Type */
USEFORMNS("..\..\experts\repository\ExceptionDialog\JclOtaExcDlgLogFrame.pas", Jclotaexcdlglogframe, JclOtaExcDlgLogPage); /* TFrame: File Type */
USEFORMNS("..\..\experts\repository\ExceptionDialog\JclOtaExcDlgTraceFrame.pas", Jclotaexcdlgtraceframe, JclOtaExcDlgTracePage); /* TFrame: File Type */
USEFORMNS("..\..\experts\repository\ExceptionDialog\JclOtaExcDlgThreadFrame.pas", Jclotaexcdlgthreadframe, JclOtaExcDlgThreadPage); /* TFrame: File Type */
USEFORMNS("..\..\experts\repository\ExceptionDialog\JclOtaExcDlgIgnoreFrame.pas", Jclotaexcdlgignoreframe, JclOtaExcDlgIgnoredPage); /* TFrame: File Type */
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------
//   Package source.
//---------------------------------------------------------------------------
#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

