//---------------------------------------------------------------------------
/*
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JclStackTraceViewerExpert-D.xml)
            
     Last generated: 24-07-2009  09:49:30 UTC     
-----------------------------------------------------------------------------
*/

#include <vcl.h>
#include <windows.h>
#pragma hdrstop
USEFORMNS("..\..\experts\stacktraceviewer\JclStackTraceViewerExceptInfoFrame.pas", Jclstacktraceviewerexceptinfoframe, frmException); /* TFrame: File Type */
USEFORMNS("..\..\experts\stacktraceviewer\JclStackTraceViewerStackFrame.pas", Jclstacktraceviewerstackframe, frmStack); /* TFrame: File Type */
USEFORMNS("..\..\experts\stacktraceviewer\JclStackTraceViewerThreadFrame.pas", Jclstacktraceviewerthreadframe, frmThread); /* TFrame: File Type */
USEFORMNS("..\..\experts\stacktraceviewer\JclStackTraceViewerModuleFrame.pas", Jclstacktraceviewermoduleframe, frmModule); /* TFrame: File Type */
USEFORMNS("..\..\experts\stacktraceviewer\JclStackTraceViewerMainFormDelphi.pas", Jclstacktraceviewermainformdelphi, frmStackView); 
USEFORMNS("..\..\experts\stacktraceviewer\JclStackTraceViewerMainFrame.pas", Jclstacktraceviewermainframe, frmMain); /* TFrame: File Type */
USEFORMNS("..\..\experts\stacktraceviewer\JclStackTraceViewerConfigFrame.pas", Jclstacktraceviewerconfigframe, JclStackTraceViewerConfigFrame); /* TFrame: File Type */
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------
//   Package source.
//---------------------------------------------------------------------------
#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------

