{
-----------------------------------------------------------------------------
     DO NOT EDIT THIS FILE, IT IS GENERATED BY THE PACKAGE GENERATOR
            ALWAYS EDIT THE RELATED XML FILE (JclDeveloperTools-R.xml)

     Last generated: 14-08-2012  09:49:00 UTC
-----------------------------------------------------------------------------
}

unit JclDeveloperTools; 

interface

uses
  JclCompilerUtils,
  JclDevToolsResources,
  JclExprEval,
  JclIDEUtils,
  JclUsesUtils,
  JclHelpUtils,
  JclMsBuild,
  MSHelpServices_TLB
  ;

implementation

end.
