unit Alcinoe.WinApi.NCrypt;

// ***************************************************************** //
// This unit was automatically generated by CHeaderWrapperGenerator. //
// Do not edit manually.                                             //
// ***************************************************************** //

interface

{$I Alcinoe.inc}

{$WARN SYMBOL_PLATFORM OFF}
{$SCOPEDENUMS OFF}
{$MINENUMSIZE 4}
{$A+}

uses
  WinApi.Windows,
  Alcinoe.WinApi.BCrypt;

type
  HCRYPTPROV = ULONG_PTR;
  HCRYPTKEY = ULONG_PTR;

// #define __NCRYPT_H__

type SECURITY_STATUS = LONG;
// #define __SECSTATUS_DEFINED__

//
// Maximum length of Key name, in characters
//
const NCRYPT_MAX_KEY_NAME_LENGTH = 512;

//
// Maximum length of Algorithm name, in characters
//
const NCRYPT_MAX_ALG_ID_LENGTH = 512;

// ***************************************************************************
//
//  NCRYPT memory management routines for functions that require
//  the caller to allocate memory
//
// ****************************************************************************
type
  PFN_NCRYPT_ALLOC = function (
    cbSize: SIZE_T): LPVOID; stdcall;

type
  PFN_NCRYPT_FREE = procedure (
    pv: LPVOID); stdcall;

type
  NCRYPT_ALLOC_PARA = record
    cbSize: DWORD; // size of this structure
    pfnAlloc: PFN_NCRYPT_ALLOC;
    pfnFree: PFN_NCRYPT_FREE;
  end;

//
// Microsoft built-in providers.
//

const MS_KEY_STORAGE_PROVIDER = 'Microsoft Software Key Storage Provider';
const MS_SMART_CARD_KEY_STORAGE_PROVIDER = 'Microsoft Smart Card Key Storage Provider';
const MS_PLATFORM_KEY_STORAGE_PROVIDER = 'Microsoft Platform Crypto Provider';
const MS_NGC_KEY_STORAGE_PROVIDER = 'Microsoft Passport Key Storage Provider';
const MS_PLUTON_CRYPTO_PROVIDER = 'Microsoft Pluton Cryptographic Provider';

//
// Key name for sealing
//
const TPM_RSA_SRK_SEAL_KEY = 'MICROSOFT_PCP_KSP_RSA_SEAL_KEY_3BD1C4BF-004E-4E2F-8A4D-0BF633DCB074';

//
// Common algorithm identifiers.
//

const NCRYPT_RSA_ALGORITHM = BCRYPT_RSA_ALGORITHM;
const NCRYPT_RSA_SIGN_ALGORITHM = BCRYPT_RSA_SIGN_ALGORITHM;
const NCRYPT_DH_ALGORITHM = BCRYPT_DH_ALGORITHM;
const NCRYPT_DSA_ALGORITHM = BCRYPT_DSA_ALGORITHM;
const NCRYPT_MD2_ALGORITHM = BCRYPT_MD2_ALGORITHM;
const NCRYPT_MD4_ALGORITHM = BCRYPT_MD4_ALGORITHM;
const NCRYPT_MD5_ALGORITHM = BCRYPT_MD5_ALGORITHM;
const NCRYPT_SHA1_ALGORITHM = BCRYPT_SHA1_ALGORITHM;
const NCRYPT_SHA256_ALGORITHM = BCRYPT_SHA256_ALGORITHM;
const NCRYPT_SHA384_ALGORITHM = BCRYPT_SHA384_ALGORITHM;
const NCRYPT_SHA512_ALGORITHM = BCRYPT_SHA512_ALGORITHM;
const NCRYPT_ECDSA_P256_ALGORITHM = BCRYPT_ECDSA_P256_ALGORITHM;
const NCRYPT_ECDSA_P384_ALGORITHM = BCRYPT_ECDSA_P384_ALGORITHM;
const NCRYPT_ECDSA_P521_ALGORITHM = BCRYPT_ECDSA_P521_ALGORITHM;
const NCRYPT_ECDH_P256_ALGORITHM = BCRYPT_ECDH_P256_ALGORITHM;
const NCRYPT_ECDH_P384_ALGORITHM = BCRYPT_ECDH_P384_ALGORITHM;
const NCRYPT_ECDH_P521_ALGORITHM = BCRYPT_ECDH_P521_ALGORITHM;

const NCRYPT_AES_ALGORITHM = BCRYPT_AES_ALGORITHM;
const NCRYPT_RC2_ALGORITHM = BCRYPT_RC2_ALGORITHM;
const NCRYPT_3DES_ALGORITHM = BCRYPT_3DES_ALGORITHM;
const NCRYPT_DES_ALGORITHM = BCRYPT_DES_ALGORITHM;
const NCRYPT_DESX_ALGORITHM = BCRYPT_DESX_ALGORITHM;
const NCRYPT_3DES_112_ALGORITHM = BCRYPT_3DES_112_ALGORITHM;

const NCRYPT_SP800108_CTR_HMAC_ALGORITHM = BCRYPT_SP800108_CTR_HMAC_ALGORITHM;
const NCRYPT_SP80056A_CONCAT_ALGORITHM = BCRYPT_SP80056A_CONCAT_ALGORITHM;
const NCRYPT_PBKDF2_ALGORITHM = BCRYPT_PBKDF2_ALGORITHM;
const NCRYPT_CAPI_KDF_ALGORITHM = BCRYPT_CAPI_KDF_ALGORITHM;

const NCRYPT_ECDSA_ALGORITHM = BCRYPT_ECDSA_ALGORITHM;
const NCRYPT_ECDH_ALGORITHM = BCRYPT_ECDH_ALGORITHM;

const NCRYPT_KEY_STORAGE_ALGORITHM = 'KEY_STORAGE';

//
// This algorithm is not supported by any BCrypt provider. This identifier is for creating
// persistent stored HMAC keys in the TPM KSP.
//
const NCRYPT_HMAC_SHA256_ALGORITHM = 'HMAC-SHA256';

// ML-KEM
const NCRYPT_MLKEM_ALGORITHM = BCRYPT_MLKEM_ALGORITHM;

// ML-DSA
const NCRYPT_MLDSA_ALGORITHM = BCRYPT_MLDSA_ALGORITHM;

// SLH-DSA
const NCRYPT_SLHDSA_ALGORITHM = BCRYPT_SLHDSA_ALGORITHM;

// LMS and XMSS
const NCRYPT_LMS_ALGORITHM = BCRYPT_LMS_ALGORITHM;
const NCRYPT_XMSS_ALGORITHM = BCRYPT_XMSS_ALGORITHM;

//
// Interfaces
//
const NCRYPT_CIPHER_INTERFACE = BCRYPT_CIPHER_INTERFACE;
const NCRYPT_HASH_INTERFACE = BCRYPT_HASH_INTERFACE;
const NCRYPT_ASYMMETRIC_ENCRYPTION_INTERFACE = BCRYPT_ASYMMETRIC_ENCRYPTION_INTERFACE;
const NCRYPT_SECRET_AGREEMENT_INTERFACE = BCRYPT_SECRET_AGREEMENT_INTERFACE;
const NCRYPT_SIGNATURE_INTERFACE = BCRYPT_SIGNATURE_INTERFACE;
const NCRYPT_KEY_DERIVATION_INTERFACE = BCRYPT_KEY_DERIVATION_INTERFACE;

const NCRYPT_KEY_ENCAPSULATION_INTERFACE = BCRYPT_KEY_ENCAPSULATION_INTERFACE;

const NCRYPT_KEY_STORAGE_INTERFACE = $00010001;
const NCRYPT_SCHANNEL_INTERFACE = $00010002;
const NCRYPT_SCHANNEL_SIGNATURE_INTERFACE = $00010003;
const NCRYPT_KEY_PROTECTION_INTERFACE = $00010004;

//
// algorithm groups.
//

const NCRYPT_RSA_ALGORITHM_GROUP = NCRYPT_RSA_ALGORITHM;
const NCRYPT_DH_ALGORITHM_GROUP = NCRYPT_DH_ALGORITHM;
const NCRYPT_DSA_ALGORITHM_GROUP = NCRYPT_DSA_ALGORITHM;
const NCRYPT_ECDSA_ALGORITHM_GROUP = 'ECDSA';
const NCRYPT_ECDH_ALGORITHM_GROUP = 'ECDH';

const NCRYPT_AES_ALGORITHM_GROUP = NCRYPT_AES_ALGORITHM;
const NCRYPT_RC2_ALGORITHM_GROUP = NCRYPT_RC2_ALGORITHM;
const NCRYPT_DES_ALGORITHM_GROUP = 'DES';
const NCRYPT_KEY_DERIVATION_GROUP = 'KEY_DERIVATION';

const NCRYPT_MLKEM_ALGORITHM_GROUP = 'MLKEM';
const NCRYPT_MLDSA_ALGORITHM_GROUP = 'MLDSA';
const NCRYPT_SLHDSA_ALGORITHM_GROUP = 'SLHDSA';
const NCRYPT_LMS_ALGORITHM_GROUP = NCRYPT_LMS_ALGORITHM;
const NCRYPT_XMSS_ALGORITHM_GROUP = NCRYPT_XMSS_ALGORITHM;

//
// NCrypt generic memory descriptors
//

const NCRYPTBUFFER_VERSION = 0;

const NCRYPTBUFFER_EMPTY = 0;
const NCRYPTBUFFER_DATA = 1;

const NCRYPTBUFFER_PROTECTION_DESCRIPTOR_STRING = 3; // The buffer contains a null-terminated Unicode string that contains the Protection Descriptor.
const NCRYPTBUFFER_PROTECTION_FLAGS = 4; // DWORD flags to be passed to NCryptCreateProtectionDescriptor function.

const NCRYPTBUFFER_SSL_CLIENT_RANDOM = 20;
const NCRYPTBUFFER_SSL_SERVER_RANDOM = 21;
const NCRYPTBUFFER_SSL_HIGHEST_VERSION = 22;
const NCRYPTBUFFER_SSL_CLEAR_KEY = 23;
const NCRYPTBUFFER_SSL_KEY_ARG_DATA = 24;
const NCRYPTBUFFER_SSL_SESSION_HASH = 25;

const NCRYPTBUFFER_PKCS_OID = 40;
const NCRYPTBUFFER_PKCS_ALG_OID = 41;
const NCRYPTBUFFER_PKCS_ALG_PARAM = 42;
const NCRYPTBUFFER_PKCS_ALG_ID = 43;
const NCRYPTBUFFER_PKCS_ATTRS = 44;
const NCRYPTBUFFER_PKCS_KEY_NAME = 45;
const NCRYPTBUFFER_PKCS_SECRET = 46;

const NCRYPTBUFFER_CERT_BLOB = 47;

//for threshold key attestation
const NCRYPTBUFFER_CLAIM_IDBINDING_NONCE = 48;
const NCRYPTBUFFER_CLAIM_KEYATTESTATION_NONCE = 49;
const NCRYPTBUFFER_KEY_PROPERTY_FLAGS = 50;
const NCRYPTBUFFER_ATTESTATIONSTATEMENT_BLOB = 51;
const NCRYPTBUFFER_ATTESTATION_CLAIM_TYPE = 52;
const NCRYPTBUFFER_ATTESTATION_CLAIM_CHALLENGE_REQUIRED = 53;

//for generic ecc
const NCRYPTBUFFER_ECC_CURVE_NAME = 60;
const NCRYPTBUFFER_ECC_PARAMETERS = 61;

//for TPM seal
const NCRYPTBUFFER_TPM_SEAL_PASSWORD = 70;
const NCRYPTBUFFER_TPM_SEAL_POLICYINFO = 71;
const NCRYPTBUFFER_TPM_SEAL_TICKET = 72;
const NCRYPTBUFFER_TPM_SEAL_NO_DA_PROTECTION = 73;

// for TPM platform attestation statements
const NCRYPTBUFFER_TPM_PLATFORM_CLAIM_PCR_MASK = 80;
const NCRYPTBUFFER_TPM_PLATFORM_CLAIM_NONCE = 81;
const NCRYPTBUFFER_TPM_PLATFORM_CLAIM_STATIC_CREATE = 82;

const NCRYPTBUFFER_ATTESTATION_STATEMENT_SIGNATURE_HASH = 90;
const NCRYPTBUFFER_ATTESTATION_STATEMENT_SIGNATURE_PADDING_SCHEME = 91;
const NCRYPTBUFFER_ATTESTATION_STATEMENT_SIGNATURE_PADDING_ALGO = 92;
const NCRYPTBUFFER_ATTESTATION_STATEMENT_SIGNATURE_PADDING_SALT_SIZE = 93;
const NCRYPTBUFFER_ATTESTATION_STATEMENT_SIGNATURE_PADDING_SALT = NCRYPTBUFFER_ATTESTATION_STATEMENT_SIGNATURE_PADDING_SALT_SIZE; // Added to avoid failure for existing users
const NCRYPTBUFFER_ATTESTATION_STATEMENT_NONCE = NCRYPTBUFFER_CLAIM_KEYATTESTATION_NONCE;

const NCRYPTBUFFER_VBS_ATTESTATION_STATEMENT_ROOT_DETAILS = 94;
const NCRYPTBUFFER_VBS_ATTESTATION_STATEMENT_IDENTITY_DETAILS = 95;

const NCRYPTBUFFER_PKCS_AES_KEY_BITS = 96;
const NCRYPTBUFFER_PKCS_PADDING_ALGO = 97;
const NCRYPTBUFFER_PKCS_PADDING_LABEL = 98;

// NCRYPT shares the same BCRYPT definitions
type NCryptBuffer = BCryptBuffer;
type PNCryptBuffer = ^BCryptBuffer;
type NCryptBufferDesc = BCryptBufferDesc;
type PNCryptBufferDesc = ^BCryptBufferDesc;

//
// NCrypt handles
//

type NCRYPT_HANDLE = ULONG_PTR;
type NCRYPT_PROV_HANDLE = ULONG_PTR;
type PNCRYPT_PROV_HANDLE = ^NCRYPT_PROV_HANDLE;
type NCRYPT_KEY_HANDLE = ULONG_PTR;
type PNCRYPT_KEY_HANDLE = ^NCRYPT_KEY_HANDLE;
type NCRYPT_HASH_HANDLE = ULONG_PTR;
type NCRYPT_SECRET_HANDLE = ULONG_PTR;
type PNCRYPT_SECRET_HANDLE = ^NCRYPT_SECRET_HANDLE;

type
  _NCRYPT_CIPHER_PADDING_INFO = record
    // size of this struct
    cbSize: ULONG;
    // See NCRYPT_CIPHER_ flag values
    dwFlags: DWORD;
    //[in, out, optional]
    // The address of a buffer that contains the initialization vector (IV) to use during encryption.
    // The cbIV parameter contains the size of this buffer. This function will modify the contents of this buffer.
    // If you need to reuse the IV later, make sure you make a copy of this buffer before calling this function.
    pbIV: PUCHAR;
    cbIV: ULONG;
    //[in, out, optional]
    // The address of a buffer that contains the algorithm specific info to use during encryption.
    // The cbOtherInfo parameter contains the size of this buffer. This function will modify the contents of this buffer.
    // If you need to reuse the buffer later, make sure you make a copy of this buffer before calling this function.
    // For Microsoft providers, when an authenticated encryption mode is used,
    // this parameter must point to a serialized BCRYPT_AUTHENTICATED_CIPHER_MODE_INFO structure.
    // NOTE: All pointers inside a structure must be to a data allocated within pbOtherInfo buffer.
    pbOtherInfo: PUCHAR;
    cbOtherInfo: ULONG;
  end;
  NCRYPT_CIPHER_PADDING_INFO = _NCRYPT_CIPHER_PADDING_INFO;
  PNCRYPT_CIPHER_PADDING_INFO = ^_NCRYPT_CIPHER_PADDING_INFO;

//
// The following flags are used with NCRYPT_CIPHER_PADDING_INFO
//
const NCRYPT_CIPHER_NO_PADDING_FLAG = $00000000;
const NCRYPT_CIPHER_BLOCK_PADDING_FLAG = $00000001;
const NCRYPT_CIPHER_OTHER_PADDING_FLAG = $00000002;

const NCRYPT_PLATFORM_ATTEST_MAGIC = $44504150; // 'PAPD'

type
  _NCRYPT_PLATFORM_ATTEST_PADDING_INFO = record
    magic: ULONG; // 'PAPD'
    pcrMask: ULONG;
  end;
  NCRYPT_PLATFORM_ATTEST_PADDING_INFO = _NCRYPT_PLATFORM_ATTEST_PADDING_INFO;

const NCRYPT_KEY_ATTEST_MAGIC = $4450414b; // 'KAPD'

type
  _NCRYPT_KEY_ATTEST_PADDING_INFO = record
    magic: ULONG; // 'KAPD'
    pbKeyBlob: PUCHAR;
    cbKeyBlob: ULONG;
    pbKeyAuth: PUCHAR;
    cbKeyAuth: ULONG;
  end;
  NCRYPT_KEY_ATTEST_PADDING_INFO = _NCRYPT_KEY_ATTEST_PADDING_INFO;

//
// key attestation claim type
//

const NCRYPT_CLAIM_AUTHORITY_ONLY = $00000001;
const NCRYPT_CLAIM_SUBJECT_ONLY = $00000002;
const NCRYPT_CLAIM_AUTHORITY_AND_SUBJECT = $00000003;
//
// The NCRYPT_CLAIM_VBS_KEY_ATTESTATION_STATEMENT claim type is automatically transformed to NCRYPT_CLAIM_VBS_ROOT in
// NCryptCreateClaim and NCryptVerifyClaim.
const NCRYPT_CLAIM_VBS_KEY_ATTESTATION_STATEMENT = $00000004;
const NCRYPT_CLAIM_VBS_ROOT = $00000005;
const NCRYPT_CLAIM_VBS_IDENTITY = $00000006;
const NCRYPT_CLAIM_WEB_AUTH_SUBJECT_ONLY = $00000102;
const NCRYPT_CLAIM_UNKNOWN = $00001000;
const NCRYPT_CLAIM_PLATFORM = $00010000;

const NCRYPT_CLAIM_WEB_AUTH_SUBJECT_ONLY_V2 = $00000103;

// NCryptCreateClaim claim types, flags and buffer types

const NCRYPT_ISOLATED_KEY_FLAG_CREATED_IN_ISOLATION = $00000001; // if set, this key was generated in isolation, not imported
const NCRYPT_ISOLATED_KEY_FLAG_IMPORT_ONLY = $00000002; // if set, this key can only be used for importing other keys

const NCRYPT_ISOLATED_KEY_FLAG_PER_BOOT_KEY = $00000004; // Indicates renewed keys per boot
const NCRYPT_VBS_KEY_FLAG_CREATED_IN_ISOLATION = NCRYPT_ISOLATED_KEY_FLAG_CREATED_IN_ISOLATION;
const NCRYPT_VBS_KEY_FLAG_IMPORT_ONLY = NCRYPT_ISOLATED_KEY_FLAG_IMPORT_ONLY;
const NCRYPT_VBS_KEY_FLAG_PER_BOOT_KEY = NCRYPT_ISOLATED_KEY_FLAG_PER_BOOT_KEY;

// Indicates that the key may be used to import ephemeral keys. This is useful in pkcs11 import
const NCRYPT_VBS_KEY_FLAG_IMPORT_EPHEMERAL_ONLY = $00000008;
const NCRYPT_ISOLATED_KEY_ATTESTED_ATTRIBUTES_V0 = 0;
const NCRYPT_ISOLATED_KEY_ATTESTED_ATTRIBUTES_CURRENT_VERSION = NCRYPT_ISOLATED_KEY_ATTESTED_ATTRIBUTES_V0;

type
  _NCRYPT_ISOLATED_KEY_ATTESTED_ATTRIBUTES = record
    Version: ULONG; // set to NCRYPT_ISOLATED_KEY_ATTESTED_ATTRIBUTES_V0
    Flags: ULONG; // NCRYPT_VBS_KEY_FLAG_... flags
    cbPublicKeyBlob: ULONG;
    // pbPublicKeyBlob[cbPublicKeyBlob] - exported public key
  end;
  NCRYPT_ISOLATED_KEY_ATTESTED_ATTRIBUTES = _NCRYPT_ISOLATED_KEY_ATTESTED_ATTRIBUTES;
  PNCRYPT_ISOLATED_KEY_ATTESTED_ATTRIBUTES = ^_NCRYPT_ISOLATED_KEY_ATTESTED_ATTRIBUTES;

// #define NCRYPT_VBS_KEY_ATTESTED_ATTRIBUTES NCRYPT_ISOLATED_KEY_ATTESTED_ATTRIBUTES
// #define PNCRYPT_VBS_KEY_ATTESTED_ATTRIBUTES PNCRYPT_ISOLATED_KEY_ATTESTED_ATTRIBUTES
const NCRYPT_VBS_KEY_ATTESTED_ATTRIBUTES_CURRENT_VERSION = NCRYPT_ISOLATED_KEY_ATTESTED_ATTRIBUTES_CURRENT_VERSION;

// Structures to assist with importation of isolated keys

const NCRYPT_EXPORTED_ISOLATED_KEY_HEADER_V0 = 0;
const NCRYPT_EXPORTED_ISOLATED_KEY_HEADER_CURRENT_VERSION = NCRYPT_EXPORTED_ISOLATED_KEY_HEADER_V0;

type
  _NCRYPT_EXPORTED_ISOLATED_KEY_HEADER = record
    Version: ULONG; // Set to NCRYPT_EXPORTED_ISOLATED_KEY_HEADER_V0
    KeyUsage: ULONG; // Set to NCRYPT_ALLOW_KEY_IMPORT_FLAG for import-only keys
    PerBootKey: ULONG; // Set to TRUE if the key is to be valid in the current boot cycle only
    cbAlgName: ULONG; // Number of bytes in Unicode algorithm name following header + terminating NULL
    cbNonce: ULONG; // Number of bytes in the nonce used to encrypt the isolated key
    cbAuthTag: ULONG; // Number of bytes in authentication tag resulting from encrypting the isolated key
    cbWrappingKey: ULONG; // Number of bytes in encrypted wrapping key blob
    cbIsolatedKey: ULONG; // Number of bytes in encrypted isolated key blob
  end;
  NCRYPT_EXPORTED_ISOLATED_KEY_HEADER = _NCRYPT_EXPORTED_ISOLATED_KEY_HEADER;
  PNCRYPT_EXPORTED_ISOLATED_KEY_HEADER = ^_NCRYPT_EXPORTED_ISOLATED_KEY_HEADER;

type
  _NCRYPT_EXPORTED_ISOLATED_KEY_ENVELOPE = record
    Header: NCRYPT_EXPORTED_ISOLATED_KEY_HEADER;
    // UCHAR AlgorithmName[Header.cbAlgName] -- Unicode algorithm name including terminating NULL
    // UCHAR Nonce[Header.cbNonce] -- Nonce buffer used when encrypting isolated key
    // ---- data after this point is not integrity protected in transit
    // UCHAR AesGcmAuthTag[Header.cbAuthTag]
    // UCHAR WrappingKeyBlob[Header.cbWrappingKey] -- RSA-OAEP encrypted AES wrapping key
    // UCHAR IsolatedKeyBlob[Header.cbIsolatedKey] -- AES-GCM encrypted key to import
  end;
  NCRYPT_EXPORTED_ISOLATED_KEY_ENVELOPE = _NCRYPT_EXPORTED_ISOLATED_KEY_ENVELOPE;
  PNCRYPT_EXPORTED_ISOLATED_KEY_ENVELOPE = ^_NCRYPT_EXPORTED_ISOLATED_KEY_ENVELOPE;

// Header used for claims of type NCRYPT_CLAIM_VBS_ROOT
const NCRYPT_VBS_ROOT_ATTESTATION_HEADER_V0 = 0;
const NCRYPT_VBS_ROOT_ATTESTATION_HEADER_CURRENT_VERSION = NCRYPT_VBS_ROOT_ATTESTATION_HEADER_V0;
const VBS_ROOT_ATTESTATION_HEADER_MAGIC = $48435256; // 'VRCH' = 0x56, 0x52, 0x43, 0x48.

type
  _NCRYPT_VBS_ROOT_ATTESTATION_HEADER = record
    Magic: ULONG; // {'H', 'C', 'R', 'V'} - 'VRCH' for VBS Root Claim Header
    Version: ULONG; // Set to NCRYPT_VBS_ROOT_ATTESTATION_HEADER_CURRENT_VERSION
    cbAttributes: ULONG; // Number of bytes in attributes of the isolated key (including public key blob )
    cbNonce: ULONG; // Number of bytes in the provided nonce, can be 0 if nonce doesn't exist
    cbReport: ULONG; // Number of bytes in key isolation report from the secure kernel
    cbSignature: ULONG; // Number of bytes in the secure kernel signature over the isolation report
    // UCHAR Attributes[cbAttributes] -- Trustlet-reported attributes of the key
    // UCHAR Nonce[cbNonce] -- Nonce value to be used when hashing Attributes
    // UCHAR Report[cbReport] -- Secure kernel report including hash of Attributes, dwFlags and nonce (if available)
    // UCHAR Signature[cbSignature] -- Secure kernel signature of the report
  end;
  NCRYPT_VBS_ROOT_ATTESTATION_HEADER = _NCRYPT_VBS_ROOT_ATTESTATION_HEADER;
  PNCRYPT_VBS_ROOT_ATTESTATION_HEADER = ^_NCRYPT_VBS_ROOT_ATTESTATION_HEADER;

// Padding structure for identity claims
const NCRYPT_VBS_IDENTITY_ATTESTATION_PADDING_V0 = 0;
const NCRYPT_VBS_IDENTITY_ATTESTATION_PADDING_CURRENT_VERSION = NCRYPT_VBS_IDENTITY_ATTESTATION_PADDING_V0;

type
  _NCRYPT_VBS_IDENTITY_ATTESTATION_PADDING = record
    Version: ULONG; // Set to NCRYPT_VBS_IDENTITY_ATTESTATION_PADDING_CURRENT_VERSION
    ulPaddingScheme: ULONG; // Padding scheme of the signing algorithm that was used through claim creation.
    cbHashAlg: ULONG; // Number of bytes in Unicode name that identifies the cryptographic padding algorithm. This algorithm must be a hashing algorithm.
    ulSalt: ULONG; // Number of bytes in of the random salt to use for the padding.
    // UCHAR HashAlg[cbHashAlg] -- Unicode name of hash algorithm used through attributes signing to create padding
  end;
  NCRYPT_VBS_IDENTITY_ATTESTATION_PADDING = _NCRYPT_VBS_IDENTITY_ATTESTATION_PADDING;
  PNCRYPT_VBS_IDENTITY_ATTESTATION_PADDING = ^_NCRYPT_VBS_IDENTITY_ATTESTATION_PADDING;

//  Header used for claims of type NCRYPT_CLAIM_VBS_IDENTITY
const NCRYPT_VBS_IDENTITY_ATTESTATION_HEADER_V0 = 0;
const NCRYPT_VBS_IDENTITY_ATTESTATION_HEADER_CURRENT_VERSION = NCRYPT_VBS_IDENTITY_ATTESTATION_HEADER_V0;
const VBS_IDENTITY_ATTESTATION_HEADER_MAGIC = $48434956; // 'VICH' = 0x56, 0x49, 0x43, 0x48.

type
  _NCRYPT_VBS_IDENTITY_ATTESTATION_HEADER = record
    Magic: ULONG; // {'H', 'C', 'I', 'V'} - 'VICH' for VBS Identity Claim Header
    Version: ULONG; // Set to NCRYPT_VBS_IDENTITY_ATTESTATION_HEADER_CURRENT_VERSION
    cbAttributes: ULONG; // Number of bytes in attributes of the isolated key (including public key blob )
    cbNonce: ULONG; // Number of bytes in the provided nonce, can be 0 if nonce doesn't exist
    cbHashAlg: ULONG; // Number of bytes in Unicode name of hash algorithm used
    cbPadding: ULONG; // Padding info (scheme and more) of the signing algorithm that was used through claim creation
    cbSignatureAlg: ULONG; // Number of bytes in Unicode name of the signing hash algorithm used
    cbSignature: ULONG; // Number of bytes in the signature over the hash of Attributes, dwFlags and nonce (if available)
    // UCHAR Attributes[cbAttributes] -- Trustlet-reported attributes of the subject key blob
    // UCHAR Nonce[cbNonce] -- Nonce value to be used when hashing Attributes
    // UCHAR HashAlg[cbHashAlg] -- Unicode name of hash algorithm used through attributes signing
    // UCHAR Padding[cbPadding] -- Padding information that is set through identity hash signing
    // UCHAR SignatureAlg[cbSignatureAlg] -- Unicode name of signing algorithm used
    // UCHAR Signature[cbSignature] -- Signature over the hash of Attributes and nonce (if available)
  end;
  NCRYPT_VBS_IDENTITY_ATTESTATION_HEADER = _NCRYPT_VBS_IDENTITY_ATTESTATION_HEADER;
  PNCRYPT_VBS_IDENTITY_ATTESTATION_HEADER = ^_NCRYPT_VBS_IDENTITY_ATTESTATION_HEADER;

const NCRYPT_VBS_KEY_ATTESTATION_STATEMENT_V1 = 1;
const NCRYPT_VBS_KEY_ATTESTATION_STATEMENT_V2 = 2;
const NCRYPT_VBS_KEY_ATTESTATION_STATEMENT_CURRENT_VERSION = NCRYPT_VBS_KEY_ATTESTATION_STATEMENT_V2;
const VBS_KEY_ATTESTATION_STATEMENT_MAGIC = $53414B56; // 'VKAS' = 0x56, 0x4B, 0x41, 0x53.

type
  _NCRYPT_VBS_KEY_ATTESTATION_STATEMENT = record
    Magic: ULONG; // {'S', 'A', 'K', 'V'} - 'VKAS' for VBS Key Attestation Statement
    Version: ULONG; // Set to NCRYPT_VBS_KEY_ATTESTATION_STATEMENT_CURRENT_VERSION
    ClaimType: ULONG; // The claim type in the memory that follows this structure
    // Root binary data - NCRYPT_VBS_ROOT_ATTESTATION_HEADER
    // UCHAR Attributes[cbAttributes] -- Trustlet-reported attributes of the key
    // UCHAR Nonce[cbNonce] -- Nonce value to be used when hashing Attributes
    // UCHAR Report[cbReport] -- Secure kernel report including hash of Attributes, dwFlags and nonce (if available)
    // UCHAR Signature[cbSignature] -- Secure kernel signature of the report
    // --------------------------------------------------------------------------------------
    // Identity binary data - NCRYPT_VBS_IDENTITY_ATTESTATION_HEADER
    // UCHAR Attributes[cbAttributes] -- Trustlet-reported attributes of the subject key blob
    // UCHAR Nonce[cbNonce] -- Nonce value to be used when hashing Attributes
    // UCHAR HashAlg[cbHashAlg] -- Unicode name of hash algorithm used through attributes signing
    // UCHAR Padding[cbPadding] -- Padding information that is set through identity hash signing
    // UCHAR SignatureAlg[cbSignatureAlg] -- Unicode name of signing algorithm used
    // UCHAR Signature[cbSignature] -- Signature over the hash of Attributes and nonce (if available)
  end;
  NCRYPT_VBS_KEY_ATTESTATION_STATEMENT = _NCRYPT_VBS_KEY_ATTESTATION_STATEMENT;
  PNCRYPT_VBS_KEY_ATTESTATION_STATEMENT = ^_NCRYPT_VBS_KEY_ATTESTATION_STATEMENT;

type
  _NCRYPT_VBS_ROOT_KEY_ATTESTATION_CLAIM_DETAILS = record
    ulKeyFlags: ULONG; // NCRYPT_ISOLATED_KEY_ flags
    ullTrustletId: ULONGLONG; // Trustlet ID
    ulTrustletSecurityVersion: ULONG; // Trustlet Security Version Number
    ulTrustletDebuggable: ULONG; // Indicates that the Trustlet can be debugged
  end;
  NCRYPT_VBS_ROOT_KEY_ATTESTATION_CLAIM_DETAILS = _NCRYPT_VBS_ROOT_KEY_ATTESTATION_CLAIM_DETAILS;
  PNCRYPT_VBS_ROOT_KEY_ATTESTATION_CLAIM_DETAILS = ^_NCRYPT_VBS_ROOT_KEY_ATTESTATION_CLAIM_DETAILS;

type
  _NCRYPT_VBS_IDENTITY_KEY_ATTESTATION_CLAIM_DETAILS = record
    ulKeyFlags: ULONG; // NCRYPT_ISOLATED_KEY_ flags
    pszSignatureHashAlg: LPCWSTR; // A pointer to a Unicode string of the claim signature hash algorithm
    ulPaddingScheme: ULONG; // Padding scheme of the signing algorithm that was used through claim creation
    pszPaddingHashAlg: LPCWSTR; // A pointer to a Unicode string of the claim padding hash algorithm
    ulPaddingSalt: ULONG; // Padding salt of the signing algorithm that was used through claim creation
  end;
  NCRYPT_VBS_IDENTITY_KEY_ATTESTATION_CLAIM_DETAILS = _NCRYPT_VBS_IDENTITY_KEY_ATTESTATION_CLAIM_DETAILS;
  PNCRYPT_VBS_IDENTITY_KEY_ATTESTATION_CLAIM_DETAILS = ^_NCRYPT_VBS_IDENTITY_KEY_ATTESTATION_CLAIM_DETAILS;

type
  __NCRYPT_PCP_TPM_WEB_AUTHN_ATTESTATION_STATEMENT = record
    Magic: UINT32; // { 'A', 'W', 'A', 'K' } - 'KAWA'
    Version: UINT32; // 1 for the statement defined in this specification
    HeaderSize: UINT32; // 24
    cbCertifyInfo: UINT32;
    cbSignature: UINT32;
    cbTpmPublic: UINT32;
    // CertifyInfo[cbCertifyInfo];
    // Signature[cbSignature];
    // TpmPublic[cbTpmPublic];
  end;
  NCRYPT_PCP_TPM_WEB_AUTHN_ATTESTATION_STATEMENT = __NCRYPT_PCP_TPM_WEB_AUTHN_ATTESTATION_STATEMENT;
  PNCRYPT_PCP_TPM_WEB_AUTHN_ATTESTATION_STATEMENT = ^__NCRYPT_PCP_TPM_WEB_AUTHN_ATTESTATION_STATEMENT;

const NCRYPT_TPM_PLATFORM_ATTESTATION_STATEMENT_V0 = 0;
const NCRYPT_TPM_PLATFORM_ATTESTATION_STATEMENT_CURRENT_VERSION = NCRYPT_TPM_PLATFORM_ATTESTATION_STATEMENT_V0;

type
  _NCRYPT_TPM_PLATFORM_ATTESTATION_STATEMENT = record
    Magic: ULONG; // {'A', 'L', 'P', 'T'} - 'TPLA' for TPM Platform
    Version: ULONG; // Set to NCRYPT_TPM_PLATFORM_ATTESTATION_STATEMENT_CURRENT_VERSION
    pcrAlg: ULONG; // The TPM hash algorithm ID
    cbSignature: ULONG; // TPMT_SIGNATURE structure signature over the quote
    cbQuote: ULONG; // TPMS_ATTEST structure that was generated and signed
    cbPcrs: ULONG; // Raw concatenation of all 24 PCRs
    // UCHAR Signature[cbSignature]
    // UCHAR Quote[cbQuote]
    // UCHAR Pcrs[cbPcrs]
  end;
  NCRYPT_TPM_PLATFORM_ATTESTATION_STATEMENT = _NCRYPT_TPM_PLATFORM_ATTESTATION_STATEMENT;
  PNCRYPT_TPM_PLATFORM_ATTESTATION_STATEMENT = ^_NCRYPT_TPM_PLATFORM_ATTESTATION_STATEMENT;

//
// NCrypt API Flags
//

const NCRYPT_NO_PADDING_FLAG = $00000001; // NCryptEncrypt/Decrypt
const NCRYPT_PAD_PKCS1_FLAG = $00000002; // NCryptEncrypt/Decrypt NCryptSignHash/VerifySignature
const NCRYPT_PAD_OAEP_FLAG = $00000004; // BCryptEncrypt/Decrypt
const NCRYPT_PAD_PSS_FLAG = $00000008; // BCryptSignHash/VerifySignature
const NCRYPT_PAD_CIPHER_FLAG = $00000010; // NCryptEncrypt/Decrypt
const NCRYPT_PAD_PQDSA_FLAG = BCRYPT_PAD_PQDSA; // BCryptSignHash/VerifySignature NCryptSignHash/VerifySignature

const NCRYPT_ATTESTATION_FLAG = $00000020; // NCryptDecrypt for key attestation

const NCRYPT_SEALING_FLAG = $00000100; // NCryptEncrypt/Decrypt for sealing

const NCRYPT_REGISTER_NOTIFY_FLAG = $00000001; // NCryptNotifyChangeKey
const NCRYPT_UNREGISTER_NOTIFY_FLAG = $00000002; // NCryptNotifyChangeKey
const NCRYPT_NO_KEY_VALIDATION = BCRYPT_NO_KEY_VALIDATION;
const NCRYPT_MACHINE_KEY_FLAG = $00000020; // same as CAPI CRYPT_MACHINE_KEYSET
const NCRYPT_SILENT_FLAG = $00000040; // same as CAPI CRYPT_SILENT
const NCRYPT_OVERWRITE_KEY_FLAG = $00000080;
const NCRYPT_WRITE_KEY_TO_LEGACY_STORE_FLAG = $00000200;
const NCRYPT_DO_NOT_FINALIZE_FLAG = $00000400;
const NCRYPT_EXPORT_LEGACY_FLAG = $00000800;
const NCRYPT_IGNORE_DEVICE_STATE_FLAG = $00001000; // NCryptOpenStorageProvider
const NCRYPT_TREAT_NIST_AS_GENERIC_ECC_FLAG = $00002000;
const NCRYPT_NO_CACHED_PASSWORD = $00004000;
const NCRYPT_PROTECT_TO_LOCAL_SYSTEM = $00008000;
const NCRYPT_USE_RECOVERY_LDAP_PORT = $00010000;
const NCRYPT_REQUIRE_KDS_LRPC_BIND_FLAG = $20000000;
const NCRYPT_PERSIST_ONLY_FLAG = $40000000;
const NCRYPT_PERSIST_FLAG = $80000000;

const NCRYPT_PREFER_VIRTUAL_ISOLATION_FLAG = $00010000; // NCryptCreatePersistedKey NCryptImportKey
const NCRYPT_USE_VIRTUAL_ISOLATION_FLAG = $00020000; // NCryptCreatePersistedKey NCryptImportKey
const NCRYPT_USE_PER_BOOT_KEY_FLAG = $00040000; // NCryptCreatePersistedKey NCryptImportKey

const NCRYPT_PREFER_VBS_FLAG = NCRYPT_PREFER_VIRTUAL_ISOLATION_FLAG; // NCryptCreatePersistedKey NCryptImportKey
const NCRYPT_REQUIRE_VBS_FLAG = NCRYPT_USE_VIRTUAL_ISOLATION_FLAG; // NCryptCreatePersistedKey NCryptImportKey
const NCRYPT_USE_VBS_PER_BOOT_KEY_FLAG = NCRYPT_USE_PER_BOOT_KEY_FLAG; // NCryptCreatePersistedKey NCryptImportKey
const NCRYPT_VBS_RETURN_CLAIM_DETAILS_FLAG = $00100000; // NCryptVerifyClaim

//
// Functions used to manage persisted keys.
//

// NCryptOpenStorageProvider flags
// #define NCRYPT_SILENT_FLAG 0x00000040 // same as CAPI CRYPT_SILENT
// #define NCRYPT_IGNORE_DEVICE_STATE_FLAG 0x00001000 // NCryptOpenStorageProvider

function NCryptOpenStorageProvider(
           phProvider: PNCRYPT_PROV_HANDLE;
           pszProviderName: LPCWSTR;
           dwFlags: DWORD): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

// AlgOperations flags for use with NCryptEnumAlgorithms()
const NCRYPT_CIPHER_OPERATION = BCRYPT_CIPHER_OPERATION;
const NCRYPT_HASH_OPERATION = BCRYPT_HASH_OPERATION;
const NCRYPT_ASYMMETRIC_ENCRYPTION_OPERATION = BCRYPT_ASYMMETRIC_ENCRYPTION_OPERATION;
const NCRYPT_SECRET_AGREEMENT_OPERATION = BCRYPT_SECRET_AGREEMENT_OPERATION;
const NCRYPT_SIGNATURE_OPERATION = BCRYPT_SIGNATURE_OPERATION;
const NCRYPT_RNG_OPERATION = BCRYPT_RNG_OPERATION;
const NCRYPT_KEY_DERIVATION_OPERATION = BCRYPT_KEY_DERIVATION_OPERATION;
const NCRYPT_KEY_ENCAPSULATION_OPERATION = BCRYPT_KEY_ENCAPSULATION_OPERATION;
// USE EXTREME CAUTION: editing comments that contain "certenrolls_*" tokens
// could break building CertEnroll idl files:
// certenrolls_begin -- NCryptAlgorithmName
type
  _NCryptAlgorithmName = record
    pszName: LPWSTR;
    dwClass: DWORD; // the CNG interface that supports this algorithm
    dwAlgOperations: DWORD; // the types of operations supported by this algorithm
    dwFlags: DWORD;
  end;
  NCryptAlgorithmName = _NCryptAlgorithmName;
  PNCryptAlgorithmName = ^NCryptAlgorithmName;
  PPNCryptAlgorithmName = ^PNCryptAlgorithmName;
// certenrolls_end

function NCryptEnumAlgorithms(
           hProvider: NCRYPT_PROV_HANDLE;
           dwAlgOperations: DWORD;
           pdwAlgCount: PDWORD;
           ppAlgList: PPNCryptAlgorithmName;
           dwFlags: DWORD): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

function NCryptIsAlgSupported(
           hProvider: NCRYPT_PROV_HANDLE;
           pszAlgId: LPCWSTR;
           dwFlags: DWORD): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

// NCryptEnumKeys flags
// #define NCRYPT_MACHINE_KEY_FLAG 0x00000020

type
  NCryptKeyName = record
    pszName: LPWSTR;
    pszAlgid: LPWSTR;
    dwLegacyKeySpec: DWORD;
    dwFlags: DWORD;
  end;
  PNCryptKeyName = ^NCryptKeyName;
  PPNCryptKeyName = ^PNCryptKeyName;

function NCryptEnumKeys(
           hProvider: NCRYPT_PROV_HANDLE;
           pszScope: LPCWSTR;
           ppKeyName: PPNCryptKeyName;
           ppEnumState: PPVOID;
           dwFlags: DWORD): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

type
  NCryptProviderName = record
    pszName: LPWSTR;
    pszComment: LPWSTR;
  end;
  PNCryptProviderName = ^NCryptProviderName;
  PPNCryptProviderName = ^PNCryptProviderName;

function NCryptEnumStorageProviders(
           pdwProviderCount: PDWORD;
           ppProviderList: PPNCryptProviderName;
           dwFlags: DWORD): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

function NCryptFreeBuffer(
           pvInput: PVOID): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

// NCryptOpenKey flags
// #define NCRYPT_MACHINE_KEY_FLAG 0x00000020
// #define NCRYPT_SILENT_FLAG 0x00000040
const NCRYPT_AUTHORITY_KEY_FLAG = $00000100;
const NCRYPT_EXTENDED_ERRORS_FLAG = $10000000;

function NCryptOpenKey(
           hProvider: NCRYPT_PROV_HANDLE;
           phKey: PNCRYPT_KEY_HANDLE;
           pszKeyName: LPCWSTR;
           dwLegacyKeySpec: DWORD;
           dwFlags: DWORD): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

// NCryptCreatePersistedKey flags
// #define NCRYPT_MACHINE_KEY_FLAG 0x00000020
// #define NCRYPT_OVERWRITE_KEY_FLAG 0x00000080

function NCryptCreatePersistedKey(
           hProvider: NCRYPT_PROV_HANDLE;
           phKey: PNCRYPT_KEY_HANDLE;
           pszAlgId: LPCWSTR;
           pszKeyName: LPCWSTR;
           dwLegacyKeySpec: DWORD;
           dwFlags: DWORD): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

// Standard property names.
const NCRYPT_NAME_PROPERTY = 'Name';
const NCRYPT_EPHEMERAL_NAME_PROPERTY = 'Ephemeral Name';
const NCRYPT_UNIQUE_NAME_PROPERTY = 'Unique Name';
const NCRYPT_ALGORITHM_PROPERTY = 'Algorithm Name';
const NCRYPT_LENGTH_PROPERTY = 'Length';
const NCRYPT_LENGTHS_PROPERTY = 'Lengths';
const NCRYPT_BLOCK_LENGTH_PROPERTY = 'Block Length';

const NCRYPT_PUBLIC_LENGTH_PROPERTY = BCRYPT_PUBLIC_KEY_LENGTH;
const NCRYPT_SIGNATURE_LENGTH_PROPERTY = BCRYPT_SIGNATURE_LENGTH;

const NCRYPT_CHAINING_MODE_PROPERTY = 'Chaining Mode';
const NCRYPT_AUTH_TAG_LENGTH = 'AuthTagLength';

const NCRYPT_UI_POLICY_PROPERTY = 'UI Policy';
const NCRYPT_EXPORT_POLICY_PROPERTY = 'Export Policy';
const NCRYPT_WINDOW_HANDLE_PROPERTY = 'HWND Handle';
const NCRYPT_USE_CONTEXT_PROPERTY = 'Use Context';
const NCRYPT_IMPL_TYPE_PROPERTY = 'Impl Type';
const NCRYPT_KEY_USAGE_PROPERTY = 'Key Usage';
const NCRYPT_KEY_TYPE_PROPERTY = 'Key Type';
const NCRYPT_VERSION_PROPERTY = 'Version';
const NCRYPT_SECURITY_DESCR_SUPPORT_PROPERTY = 'Security Descr Support';
const NCRYPT_SECURITY_DESCR_PROPERTY = 'Security Descr';
const NCRYPT_USE_COUNT_ENABLED_PROPERTY = 'Enabled Use Count';
const NCRYPT_USE_COUNT_PROPERTY = 'Use Count';
const NCRYPT_LAST_MODIFIED_PROPERTY = 'Modified';
const NCRYPT_MAX_NAME_LENGTH_PROPERTY = 'Max Name Length';
const NCRYPT_ALGORITHM_GROUP_PROPERTY = 'Algorithm Group';
const NCRYPT_DH_PARAMETERS_PROPERTY = BCRYPT_DH_PARAMETERS;

const NCRYPT_ECC_PARAMETERS_PROPERTY = BCRYPT_ECC_PARAMETERS;
const NCRYPT_ECC_CURVE_NAME_PROPERTY = BCRYPT_ECC_CURVE_NAME;
const NCRYPT_ECC_CURVE_NAME_LIST_PROPERTY = BCRYPT_ECC_CURVE_NAME_LIST;

const NCRYPT_USE_VIRTUAL_ISOLATION_PROPERTY = 'Virtual Iso';
const NCRYPT_USE_PER_BOOT_KEY_PROPERTY = 'Per Boot Key';

const NCRYPT_PROVIDER_HANDLE_PROPERTY = 'Provider Handle';
const NCRYPT_PIN_PROPERTY = 'SmartCardPin';
const NCRYPT_READER_PROPERTY = 'SmartCardReader';
const NCRYPT_SMARTCARD_GUID_PROPERTY = 'SmartCardGuid';
const NCRYPT_CERTIFICATE_PROPERTY = 'SmartCardKeyCertificate';
const NCRYPT_PIN_PROMPT_PROPERTY = 'SmartCardPinPrompt';
const NCRYPT_USER_CERTSTORE_PROPERTY = 'SmartCardUserCertStore';
const NCRYPT_ROOT_CERTSTORE_PROPERTY = 'SmartcardRootCertStore';
const NCRYPT_SECURE_PIN_PROPERTY = 'SmartCardSecurePin';
const NCRYPT_ASSOCIATED_ECDH_KEY = 'SmartCardAssociatedECDHKey';
const NCRYPT_SCARD_PIN_ID = 'SmartCardPinId';
const NCRYPT_SCARD_PIN_INFO = 'SmartCardPinInfo';
const NCRYPT_READER_ICON_PROPERTY = 'SmartCardReaderIcon';
const NCRYPT_KDF_SECRET_VALUE = 'KDFKeySecret';
const NCRYPT_DISMISS_UI_TIMEOUT_SEC_PROPERTY = 'SmartCardDismissUITimeoutSeconds';
const NCRYPT_VBS_ROOT_PUB_PROPERTY = 'VBS_ROOT_PUB';
const NCRYPT_CERTIFICATE_FROM_NVRAM_PROPERTY = 'KeyCertificateFromTpmNvram';

const NCRYPT_PARAMETER_SET_NAME_PROPERTY = BCRYPT_PARAMETER_SET_NAME; // For PQC keys

const NCRYPT_KEM_SHARED_SECRET_LENGTH_PROPERTY = BCRYPT_KEM_SHARED_SECRET_LENGTH;
const NCRYPT_KEM_CIPHERTEXT_LENGTH_PROPERTY = BCRYPT_KEM_CIPHERTEXT_LENGTH;

//
// Additional property strings specific for the Platform Crypto Provider
//
const NCRYPT_PCP_PLATFORM_TYPE_PROPERTY = 'PCP_PLATFORM_TYPE';
const NCRYPT_PCP_PROVIDER_VERSION_PROPERTY = 'PCP_PROVIDER_VERSION';
const NCRYPT_PCP_EKPUB_PROPERTY = 'PCP_EKPUB';
const NCRYPT_PCP_EKCERT_PROPERTY = 'PCP_EKCERT';
const NCRYPT_PCP_EKNVCERT_PROPERTY = 'PCP_EKNVCERT';
const NCRYPT_PCP_RSA_EKPUB_PROPERTY = 'PCP_RSA_EKPUB';
const NCRYPT_PCP_RSA_EKCERT_PROPERTY = 'PCP_RSA_EKCERT';
const NCRYPT_PCP_RSA_EKNVCERT_PROPERTY = 'PCP_RSA_EKNVCERT';
const NCRYPT_PCP_ECC_EKPUB_PROPERTY = 'PCP_ECC_EKPUB';
const NCRYPT_PCP_ECC_EKCERT_PROPERTY = 'PCP_ECC_EKCERT';
const NCRYPT_PCP_ECC_EKNVCERT_PROPERTY = 'PCP_ECC_EKNVCERT';
const NCRYPT_PCP_SRKPUB_PROPERTY = 'PCP_SRKPUB';
const NCRYPT_PCP_PCRTABLE_PROPERTY = 'PCP_PCRTABLE';
const NCRYPT_PCP_CHANGEPASSWORD_PROPERTY = 'PCP_CHANGEPASSWORD';
const NCRYPT_PCP_PASSWORD_REQUIRED_PROPERTY = 'PCP_PASSWORD_REQUIRED';
const NCRYPT_PCP_USAGEAUTH_PROPERTY = 'PCP_USAGEAUTH';
const NCRYPT_PCP_MIGRATIONPASSWORD_PROPERTY = 'PCP_MIGRATIONPASSWORD';
const NCRYPT_PCP_EXPORT_ALLOWED_PROPERTY = 'PCP_EXPORT_ALLOWED';
const NCRYPT_PCP_STORAGEPARENT_PROPERTY = 'PCP_STORAGEPARENT';
const NCRYPT_PCP_PROVIDERHANDLE_PROPERTY = 'PCP_PROVIDERMHANDLE';
const NCRYPT_PCP_PLATFORMHANDLE_PROPERTY = 'PCP_PLATFORMHANDLE';
const NCRYPT_PCP_PLATFORM_BINDING_PCRMASK_PROPERTY = 'PCP_PLATFORM_BINDING_PCRMASK';
const NCRYPT_PCP_PLATFORM_BINDING_PCRDIGESTLIST_PROPERTY = 'PCP_PLATFORM_BINDING_PCRDIGESTLIST';
const NCRYPT_PCP_PLATFORM_BINDING_PCRDIGEST_PROPERTY = 'PCP_PLATFORM_BINDING_PCRDIGEST';
const NCRYPT_PCP_KEY_USAGE_POLICY_PROPERTY = 'PCP_KEY_USAGE_POLICY';
const NCRYPT_PCP_RSA_SCHEME_PROPERTY = 'PCP_RSA_SCHEME';
const NCRYPT_PCP_TPM12_IDBINDING_PROPERTY = 'PCP_TPM12_IDBINDING';
const NCRYPT_PCP_TPM12_IDBINDING_DYNAMIC_PROPERTY = 'PCP_TPM12_IDBINDING_DYNAMIC';
const NCRYPT_PCP_TPM12_IDACTIVATION_PROPERTY = 'PCP_TPM12_IDACTIVATION';
const NCRYPT_PCP_KEYATTESTATION_PROPERTY = 'PCP_TPM12_KEYATTESTATION';
const NCRYPT_PCP_ALTERNATE_KEY_STORAGE_LOCATION_PROPERTY = 'PCP_ALTERNATE_KEY_STORAGE_LOCATION';

const NCRYPT_PCP_PLATFORM_BINDING_PCRALGID_PROPERTY = 'PCP_PLATFORM_BINDING_PCRALGID';

const NCRYPT_PCP_HMAC_AUTH_POLICYREF = 'PCP_HMAC_AUTH_POLICYREF';
const NCRYPT_PCP_HMAC_AUTH_POLICYINFO = 'PCP_HMAC_AUTH_POLICYINFO';
const NCRYPT_PCP_HMAC_AUTH_NONCE = 'PCP_HMAC_AUTH_NONCE';
const NCRYPT_PCP_HMAC_AUTH_SIGNATURE = 'PCP_HMAC_AUTH_SIGNATURE';
const NCRYPT_PCP_HMAC_AUTH_TICKET = 'PCP_HMAC_AUTH_TICKET';
const NCRYPT_PCP_NO_DA_PROTECTION_PROPERTY = 'PCP_NO_DA_PROTECTION';

const NCRYPT_PCP_TPM_MANUFACTURER_ID_PROPERTY = 'PCP_TPM_MANUFACTURER_ID';
const NCRYPT_PCP_TPM_FW_VERSION_PROPERTY = 'PCP_TPM_FW_VERSION';

const NCRYPT_PCP_TPM2BNAME_PROPERTY = 'PCP_TPM2BNAME';
const NCRYPT_PCP_TPM_VERSION_PROPERTY = 'PCP_TPM_VERSION';

const NCRYPT_PCP_RAW_POLICYDIGEST_PROPERTY = 'PCP_RAW_POLICYDIGEST';
const NCRYPT_PCP_KEY_CREATIONHASH_PROPERTY = 'PCP_KEY_CREATIONHASH';
const NCRYPT_PCP_KEY_CREATIONTICKET_PROPERTY = 'PCP_KEY_CREATIONTICKET';
const NCRYPT_PCP_RSA_SCHEME_HASH_ALG_PROPERTY = 'PCP_RSA_SCHEME_HASH_ALG';
const NCRYPT_PCP_TPM_IFX_RSA_KEYGEN_PROHIBITED_PROPERTY = 'PCP_TPM_IFX_RSA_KEYGEN_PROHIBITED';
const NCRYPT_PCP_TPM_IFX_RSA_KEYGEN_VULNERABILITY_PROPERTY = 'PCP_TPM_IFX_RSA_KEYGEN_VULNERABILITY';

// NCRYPT_PCP_TPM_IFX_RSA_KEYGEN_VULNERABILITY_PROPERTY values

const IFX_RSA_KEYGEN_VUL_NOT_AFFECTED = 0;
const IFX_RSA_KEYGEN_VUL_AFFECTED_LEVEL_1 = 1;
const IFX_RSA_KEYGEN_VUL_AFFECTED_LEVEL_2 = 2;

const NCRYPT_PCP_SESSIONID_PROPERTY = 'PCP_SESSIONID';
const NCRYPT_PCP_PSS_SALT_SIZE_PROPERTY = 'PSS Salt Size';

// TPM RSAPSS Salt size types

const NCRYPT_TPM_PSS_SALT_SIZE_UNKNOWN = $00000000;
const NCRYPT_TPM_PSS_SALT_SIZE_MAXIMUM = $00000001; // Pre-TPM Spec-1.16: Max allowed salt size
const NCRYPT_TPM_PSS_SALT_SIZE_HASHSIZE = $00000002; // Post-1.16: PSS salt = hashLen

const NCRYPT_PCP_INTERMEDIATE_CA_EKCERT_PROPERTY = 'PCP_INTERMEDIATE_CA_EKCERT';

const NCRYPT_PCP_PCRTABLE_ALGORITHM_PROPERTY = 'PCP_PCRTABLE_ALGORITHM';

const NCRYPT_PCP_SYMMETRIC_KEYBITS_PROPERTY = 'PCP_SYMMETRIC_KEYBITS';

// TPM NCryptSignHash Flag

const NCRYPT_TPM_PAD_PSS_IGNORE_SALT = $00000020; // NCryptSignHash

//
// BCRYPT_PCP_KEY_USAGE_POLICY values
//
const NCRYPT_TPM12_PROVIDER = ($00010000);
const NCRYPT_PCP_SIGNATURE_KEY = ($00000001);
const NCRYPT_PCP_ENCRYPTION_KEY = ($00000002);
const NCRYPT_PCP_GENERIC_KEY = (NCRYPT_PCP_SIGNATURE_KEY or NCRYPT_PCP_ENCRYPTION_KEY);
const NCRYPT_PCP_STORAGE_KEY = ($00000004);
const NCRYPT_PCP_IDENTITY_KEY = ($00000008);

const NCRYPT_PCP_HMACVERIFICATION_KEY = ($00000010);

//
// Additional property strings specific for the Smart Card Key Storage Provider
//
const NCRYPT_SCARD_NGC_KEY_NAME = 'SmartCardNgcKeyName';

//
// Additional property strings specific to the Pluton Cryptographic Provider
//
const NCRYPT_PLUTON_EKCERT_PROPERTY = 'PLUTON_EKCERT';
const NCRYPT_PLUTON_EKPUB_PROPERTY = 'PLUTON_EKPUB';
const NCRYPT_PLUTON_RSA_EKCERT_PROPERTY = 'PLUTON_RSA_EKCERT';
const NCRYPT_PLUTON_RSA_EKPUB_PROPERTY = 'PLUTON_RSA_EKPUB';
const NCRYPT_PLUTON_ECC_EKCERT_PROPERTY = 'PLUTON_ECC_EKCERT';
const NCRYPT_PLUTON_ECC_EKPUB_PROPERTY = 'PLUTON_ECC_EKPUB';
const NCRYPT_PLUTON_SESSION_ID_PROPERTY = 'PLUTON_SESSION_ID';
const NCRYPT_PLUTON_KDF_PARENT_KEY_UNIQUE_NAME_PROPERTY = 'PlutonKdfParentKeyUniqueName';
const NCRYPT_PLUTON_KDF_PARAMS_BUFFER_DESC_PROPERTY = 'PlutonKdfParamsBufferDesc';

//
// Used to set IV for block ciphers, before calling NCryptEncrypt/NCryptDecrypt
//
const NCRYPT_INITIALIZATION_VECTOR = BCRYPT_INITIALIZATION_VECTOR;

const NCRYPT_CHANGEPASSWORD_PROPERTY = NCRYPT_PCP_CHANGEPASSWORD_PROPERTY;
const NCRYPT_ALTERNATE_KEY_STORAGE_LOCATION_PROPERTY = NCRYPT_PCP_ALTERNATE_KEY_STORAGE_LOCATION_PROPERTY;
const NCRYPT_KEY_ACCESS_POLICY_PROPERTY = 'Key Access Policy';

// Maximum length of property name (in characters)
const NCRYPT_MAX_PROPERTY_NAME = 64;

// Maximum length of property data (in bytes)
const NCRYPT_MAX_PROPERTY_DATA = $100000;

// NCRYPT_EXPORT_POLICY_PROPERTY property flags.
const NCRYPT_ALLOW_EXPORT_FLAG = $00000001;
const NCRYPT_ALLOW_PLAINTEXT_EXPORT_FLAG = $00000002;
const NCRYPT_ALLOW_ARCHIVING_FLAG = $00000004;
const NCRYPT_ALLOW_PLAINTEXT_ARCHIVING_FLAG = $00000008;
const NCRYPT_ALLOW_PKCS11_RSA_AES_EXPORT_FLAG = $00000010;

// NCRYPT_IMPL_TYPE_PROPERTY property flags.
const NCRYPT_IMPL_HARDWARE_FLAG = $00000001;
const NCRYPT_IMPL_SOFTWARE_FLAG = $00000002;
const NCRYPT_IMPL_REMOVABLE_FLAG = $00000008;
const NCRYPT_IMPL_HARDWARE_RNG_FLAG = $00000010;
const NCRYPT_IMPL_VIRTUAL_ISOLATION_FLAG = $00000020;

// NCRYPT_KEY_USAGE_PROPERTY property flags.
const NCRYPT_ALLOW_DECRYPT_FLAG = $00000001;
const NCRYPT_ALLOW_SIGNING_FLAG = $00000002;
const NCRYPT_ALLOW_KEY_AGREEMENT_FLAG = $00000004;
const NCRYPT_ALLOW_KEY_ENVELOPE_FLAG = $00000008;
const NCRYPT_ALLOW_KEY_IMPORT_FLAG = NCRYPT_ALLOW_KEY_ENVELOPE_FLAG;
const NCRYPT_ALLOW_KEY_ATTESTATION_FLAG = $00000010;
const NCRYPT_ALLOW_KEY_IMPORT_EPHEMERAL_FLAG = $00000020;
const NCRYPT_ALLOW_ALL_USAGES = $00ffffff;

// NCRYPT_UI_POLICY_PROPERTY property flags and structure
const NCRYPT_UI_PROTECT_KEY_FLAG = $00000001;
const NCRYPT_UI_FORCE_HIGH_PROTECTION_FLAG = $00000002;
const NCRYPT_UI_FINGERPRINT_PROTECTION_FLAG = $00000004;
const NCRYPT_UI_APPCONTAINER_ACCESS_MEDIUM_FLAG = $00000008;

//
// Pin Cache Provider Properties
//

const NCRYPT_PIN_CACHE_FREE_APPLICATION_TICKET_PROPERTY = 'PinCacheFreeApplicationTicket';

const NCRYPT_PIN_CACHE_FLAGS_PROPERTY = 'PinCacheFlags';

// The NCRYPT_PIN_CACHE_FLAGS_PROPERTY property is a DWORD value that can be set from a trusted process. The
// following flags can be set.
const NCRYPT_PIN_CACHE_DISABLE_DPL_FLAG = $00000001;

//
// Pin Cache Key Properties
//

const NCRYPT_PIN_CACHE_APPLICATION_TICKET_PROPERTY = 'PinCacheApplicationTicket';
const NCRYPT_PIN_CACHE_APPLICATION_IMAGE_PROPERTY = 'PinCacheApplicationImage';
const NCRYPT_PIN_CACHE_APPLICATION_STATUS_PROPERTY = 'PinCacheApplicationStatus';
const NCRYPT_PIN_CACHE_PIN_PROPERTY = 'PinCachePin';
const NCRYPT_PIN_CACHE_IS_GESTURE_REQUIRED_PROPERTY = 'PinCacheIsGestureRequired';

const NCRYPT_PIN_CACHE_REQUIRE_GESTURE_FLAG = $00000001;

// The NCRYPT_PIN_CACHE_PIN_PROPERTY and NCRYPT_PIN_CACHE_APPLICATION_TICKET_PROPERTY properties
// return a 32 byte random unique ID encoded as a null terminated base64 Unicode string. The string length
// is 32 * 4/3 + 1 characters = 45 characters, 90 bytes
const NCRYPT_PIN_CACHE_PIN_BYTE_LENGTH = 90;
const NCRYPT_PIN_CACHE_APPLICATION_TICKET_BYTE_LENGTH = 90;

const NCRYPT_PIN_CACHE_CLEAR_PROPERTY = 'PinCacheClear';

// The NCRYPT_PIN_CACHE_CLEAR_PROPERTY property is a DWORD value. The following option can be set:
const NCRYPT_PIN_CACHE_CLEAR_FOR_CALLING_PROCESS_OPTION = $00000001;

type
  __NCRYPT_UI_POLICY = record
    dwVersion: DWORD;
    dwFlags: DWORD;
    pszCreationTitle: LPCWSTR;
    pszFriendlyName: LPCWSTR;
    pszDescription: LPCWSTR;
  end;
  NCRYPT_UI_POLICY = __NCRYPT_UI_POLICY;

const NCRYPT_KEY_ACCESS_POLICY_VERSION = 1;
const NCRYPT_ALLOW_SILENT_KEY_ACCESS = $00000001;
type
  __NCRYPT_KEY_ACCESS_POLICY_BLOB = record
    dwVersion: DWORD;
    dwPolicyFlags: DWORD;
    cbUserSid: DWORD;
    cbApplicationSid: DWORD;
    // User Sid
    // Application Sid
  end;
  NCRYPT_KEY_ACCESS_POLICY_BLOB = __NCRYPT_KEY_ACCESS_POLICY_BLOB;

// NCRYPT_LENGTHS_PROPERTY property structure.
type
  __NCRYPT_SUPPORTED_LENGTHS = record
    dwMinLength: DWORD;
    dwMaxLength: DWORD;
    dwIncrement: DWORD;
    dwDefaultLength: DWORD;
  end;
  NCRYPT_SUPPORTED_LENGTHS = __NCRYPT_SUPPORTED_LENGTHS;

// NCRYPT_PCP_HMAC_AUTH_SIGNATURE property structure.
type
  __NCRYPT_PCP_HMAC_AUTH_SIGNATURE_INFO = record
    dwVersion: DWORD;
    iExpiration: INT32;
    pabNonce: array[0..32-1] of BYTE;
    pabPolicyRef: array[0..32-1] of BYTE;
    pabHMAC: array[0..32-1] of BYTE;
  end;
  NCRYPT_PCP_HMAC_AUTH_SIGNATURE_INFO = __NCRYPT_PCP_HMAC_AUTH_SIGNATURE_INFO;

// NCRYPT_PCP_TPM_FW_VERSION property structure.
type
  __NCRYPT_PCP_TPM_FW_VERSION_INFO = record
    major1: UINT16;
    major2: UINT16;
    minor1: UINT16;
    minor2: UINT16;
  end;
  NCRYPT_PCP_TPM_FW_VERSION_INFO = __NCRYPT_PCP_TPM_FW_VERSION_INFO;

// NCRYPT_PCP_RAW_POLICYDIGEST_PROPERTY structure
type
  __NCRYPT_PCP_RAW_POLICYDIGEST = record
    dwVersion: DWORD;
    cbDigest: DWORD;
  end;
  NCRYPT_PCP_RAW_POLICYDIGEST_INFO = __NCRYPT_PCP_RAW_POLICYDIGEST;

// NCryptGetProperty flags
// #define NCRYPT_PERSIST_ONLY_FLAG 0x40000000

function NCryptGetProperty(
           hObject: NCRYPT_HANDLE;
           pszProperty: LPCWSTR;
           pbOutput: PBYTE;
           cbOutput: DWORD;
           pcbResult: PDWORD;
           dwFlags: DWORD): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

// NCryptSetProperty flags
// #define NCRYPT_PERSIST_FLAG 0x80000000
// #define NCRYPT_PERSIST_ONLY_FLAG 0x40000000

function NCryptSetProperty(
           hObject: NCRYPT_HANDLE;
           pszProperty: LPCWSTR;
           pbInput: PBYTE;
           cbInput: DWORD;
           dwFlags: DWORD): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

// NCryptFinalizeKey flags
// #define NCRYPT_WRITE_KEY_TO_LEGACY_STORE_FLAG 0x00000200

function NCryptFinalizeKey(
           hKey: NCRYPT_KEY_HANDLE;
           dwFlags: DWORD): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

function NCryptEncrypt(
           hKey: NCRYPT_KEY_HANDLE;
           pbInput: PBYTE;
           cbInput: DWORD;
           pPaddingInfo: PVOID;
           pbOutput: PBYTE;
           cbOutput: DWORD;
           pcbResult: PDWORD;
           dwFlags: DWORD): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

function NCryptDecrypt(
           hKey: NCRYPT_KEY_HANDLE;
           pbInput: PBYTE;
           cbInput: DWORD;
           pPaddingInfo: PVOID;
           pbOutput: PBYTE;
           cbOutput: DWORD;
           pcbResult: PDWORD;
           dwFlags: DWORD): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

// SECURITY_STATUS
// __CALLCONV__
// NCryptEncapsulate(
// NCRYPT_KEY_HANDLE hKey,

// PBYTE pbSecretKey,
// ULONG cbSecretKey,
// ULONG * pcbSecretKey,

// PBYTE pbCipherText,
// ULONG cbCipherText,
// ULONG * pcbCipherText,
// ULONG dwFlags);

// SECURITY_STATUS
// __CALLCONV__
// NCryptDecapsulate(
// NCRYPT_KEY_HANDLE hKey,
// PBYTE pbCipherText,
// ULONG cbCipherText,

// PBYTE pbSecretKey,
// ULONG cbSecretKey,
// ULONG * pcbSecretKey,
// ULONG dwFlags);

type
  _NCRYPT_KEY_BLOB_HEADER = record
    cbSize: ULONG; // size of this structure
    dwMagic: ULONG;
    cbAlgName: ULONG; // size of the algorithm, in bytes, including terminating 0
    cbKeyData: ULONG;
  end;
  NCRYPT_KEY_BLOB_HEADER = _NCRYPT_KEY_BLOB_HEADER;
  PNCRYPT_KEY_BLOB_HEADER = ^_NCRYPT_KEY_BLOB_HEADER;

const NCRYPT_CIPHER_KEY_BLOB_MAGIC = $52485043; // CPHR
const NCRYPT_KDF_KEY_BLOB_MAGIC = $3146444B; // KDF1
const NCRYPT_PROTECTED_KEY_BLOB_MAGIC = $4B545250; // PRTK

const NCRYPT_CIPHER_KEY_BLOB = 'CipherKeyBlob';
const NCRYPT_KDF_KEY_BLOB = 'KDFKeyBlob';
const NCRYPT_PROTECTED_KEY_BLOB = 'ProtectedKeyBlob';

type
  NCRYPT_TPM_LOADABLE_KEY_BLOB_HEADER = record
    magic: DWORD;
    cbHeader: DWORD;
    cbPublic: DWORD;
    cbPrivate: DWORD;
    cbName: DWORD;
  end;
  PNCRYPT_TPM_LOADABLE_KEY_BLOB_HEADER = ^NCRYPT_TPM_LOADABLE_KEY_BLOB_HEADER;

// #define NCRYPT_TPM_LOADABLE_KEY_BLOB_MIN_SIZE sizeof(NCRYPT_TPM_LOADABLE_KEY_BLOB_HEADER)
const NCRYPT_TPM_LOADABLE_KEY_BLOB = 'PcpTpmProtectedKeyBlob';
const NCRYPT_TPM_LOADABLE_KEY_BLOB_MAGIC = $4D54504B; // 'MTPK'

type
  NCRYPT_TPM_PERSISTENT_KEY_BLOB_HEADER = record
    magic: DWORD;
    cbHeader: DWORD;
    tpmHandle: DWORD;
  end;
  PNCRYPT_TPM_PERSISTENT_KEY_BLOB_HEADER = ^NCRYPT_TPM_PERSISTENT_KEY_BLOB_HEADER;

// #define NCRYPT_TPM_PERSISTENT_KEY_BLOB_MIN_SIZE sizeof(NCRYPT_TPM_PERSISTENT_KEY_BLOB_HEADER)
const NCRYPT_TPM_PERSISTENT_KEY_BLOB = 'PcpTpmPersistentKeyBlob';
const NCRYPT_TPM_PERSISTENT_KEY_BLOB_MAGIC = $4D54504B; // 'MTPE'

const NCRYPT_PKCS7_ENVELOPE_BLOB = 'PKCS7_ENVELOPE';
const NCRYPT_PKCS8_PRIVATE_KEY_BLOB = 'PKCS8_PRIVATEKEY';
const NCRYPT_OPAQUETRANSPORT_BLOB = 'OpaqueTransport';

const NCRYPT_ISOLATED_KEY_ENVELOPE_BLOB = 'ISOLATED_KEY_ENVELOPE';

type
  _NCRYPT_PQ_BLOB = record
    dwMagic: ULONG;
    cbBCryptType: ULONG; // Number of bytes in BCrypt blob type.
    cbBCryptBlob: ULONG; // Number of bytes in BCrypt blob data.
    // UCHAR BCryptType[cbBCryptType] -- The BCrypt blob type including '\0'. For example, BCRYPT_PQDSA_PRIVATE_BLOB or BCRYPT_PQDSA_PUBLIC_BLOB .
    // UCHAR BCryptBlob[cbBCryptBlob] -- BCrypt blob data. Currently it's BCRYPT_PQDSA_KEY_BLOB.
  end;
  NCRYPT_PQ_BLOB = _NCRYPT_PQ_BLOB;
  PNCRYPT_PQ_BLOB = ^_NCRYPT_PQ_BLOB;

const NCRYPT_PQ_PRIVATE_BLOB_MAGIC = $52505150; // PQPR

const NCRYPT_PQ_PRIVATE_KEY_BLOB = 'PQPrivateKeyBlob';
const NCRYPT_PQ_PUBLIC_KEY_BLOB = BCRYPT_PUBLIC_KEY_BLOB;

// NCryptImportKey flags
// #define NCRYPT_MACHINE_KEY_FLAG 0x00000020
// #define NCRYPT_DO_NOT_FINALIZE_FLAG 0x00000400
// #define NCRYPT_EXPORT_LEGACY_FLAG 0x00000800

function NCryptImportKey(
           hProvider: NCRYPT_PROV_HANDLE;
           hImportKey: NCRYPT_KEY_HANDLE;
           pszBlobType: LPCWSTR;
           pParameterList: PNCryptBufferDesc;
           phKey: PNCRYPT_KEY_HANDLE;
           pbData: PBYTE;
           cbData: DWORD;
           dwFlags: DWORD): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

function NCryptExportKey(
           hKey: NCRYPT_KEY_HANDLE;
           hExportKey: NCRYPT_KEY_HANDLE;
           pszBlobType: LPCWSTR;
           pParameterList: PNCryptBufferDesc;
           pbOutput: PBYTE;
           cbOutput: DWORD;
           pcbResult: PDWORD;
           dwFlags: DWORD): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

function NCryptSignHash(
           hKey: NCRYPT_KEY_HANDLE;
           pPaddingInfo: PVOID;
           pbHashValue: PBYTE;
           cbHashValue: DWORD;
           pbSignature: PBYTE;
           cbSignature: DWORD;
           pcbResult: PDWORD;
           dwFlags: DWORD): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

function NCryptVerifySignature(
           hKey: NCRYPT_KEY_HANDLE;
           pPaddingInfo: PVOID;
           pbHashValue: PBYTE;
           cbHashValue: DWORD;
           pbSignature: PBYTE;
           cbSignature: DWORD;
           dwFlags: DWORD): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

function NCryptDeleteKey(
           hKey: NCRYPT_KEY_HANDLE;
           dwFlags: DWORD): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

function NCryptFreeObject(
           hObject: NCRYPT_HANDLE): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

function NCryptIsKeyHandle(
           hKey: NCRYPT_KEY_HANDLE): LongBool; stdcall; external 'ncrypt.dll';

function NCryptTranslateHandle(
           phProvider: PNCRYPT_PROV_HANDLE;
           phKey: PNCRYPT_KEY_HANDLE;
           hLegacyProv: HCRYPTPROV;
           hLegacyKey: HCRYPTKEY;
           dwLegacyKeySpec: DWORD;
           dwFlags: DWORD): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

// NCryptNotifyChangeKey flags
// #define NCRYPT_REGISTER_NOTIFY_FLAG 0x00000001
// #define NCRYPT_UNREGISTER_NOTIFY_FLAG 0x00000002
// #define NCRYPT_MACHINE_KEY_FLAG 0x00000020

function NCryptNotifyChangeKey(
           hProvider: NCRYPT_PROV_HANDLE;
           phEvent: PHANDLE;
           dwFlags: DWORD): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

function NCryptSecretAgreement(
           hPrivKey: NCRYPT_KEY_HANDLE;
           hPubKey: NCRYPT_KEY_HANDLE;
           phAgreedSecret: PNCRYPT_SECRET_HANDLE;
           dwFlags: DWORD): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

function NCryptDeriveKey(
           hSharedSecret: NCRYPT_SECRET_HANDLE;
           pwszKDF: LPCWSTR;
           pParameterList: PNCryptBufferDesc;
           pbDerivedKey: PBYTE;
           cbDerivedKey: DWORD;
           pcbResult: PDWORD;
           dwFlags: ULONG): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

function NCryptKeyDerivation(
           hKey: NCRYPT_KEY_HANDLE;
           pParameterList: PNCryptBufferDesc;
           pbDerivedKey: PUCHAR;
           cbDerivedKey: DWORD;
           pcbResult: PDWORD;
           dwFlags: ULONG): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

function NCryptCreateClaim(
           hSubjectKey: NCRYPT_KEY_HANDLE;
           hAuthorityKey: NCRYPT_KEY_HANDLE;
           dwClaimType: DWORD;
           pParameterList: PNCryptBufferDesc;
           pbClaimBlob: PBYTE;
           cbClaimBlob: DWORD;
           pcbResult: PDWORD;
           dwFlags: DWORD): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

function NCryptVerifyClaim(
           hSubjectKey: NCRYPT_KEY_HANDLE;
           hAuthorityKey: NCRYPT_KEY_HANDLE;
           dwClaimType: DWORD;
           pParameterList: PNCryptBufferDesc;
           pbClaimBlob: PBYTE;
           cbClaimBlob: DWORD;
           pOutput: PNCryptBufferDesc;
           dwFlags: DWORD): SECURITY_STATUS; stdcall; external 'ncrypt.dll';

// #define NCRYPT_KEY_STORAGE_INTERFACE_VERSION BCRYPT_MAKE_INTERFACE_VERSION(1,0)
// #define NCRYPT_KEY_STORAGE_INTERFACE_VERSION_2 BCRYPT_MAKE_INTERFACE_VERSION(2,0)
// #define NCRYPT_KEY_STORAGE_INTERFACE_VERSION_3 BCRYPT_MAKE_INTERFACE_VERSION(3,0)
// #define NCRYPT_KEY_STORAGE_INTERFACE_VERSION_4 BCRYPT_MAKE_INTERFACE_VERSION(4,0)

implementation

end.